### ISSUE TITLE
ça donne une réponse fausse pour ces données

### ISSUE THREAD

**Issue by naziradidier** [gaetan1903/decoupage-sous-reseau#3]
![image](https://user-images.githubusercontent.com/74833519/116508719-3b7b7300-a8c2-11eb-9659-7ac69bcfd865.png)
²

**Comment by gaetan1903** [comment]
Peux tu me donner le résultat attendu pour que je puisse re-trouver le bug 

Effectivement c'est faux puisque ça depasse 256 .. 

Il faut rajouter sûrement une condition... 😋😋


Merci 😌

**Comment by gaetan1903** [comment]
Je reviens à ce sujet après analyse de tes données, 

Comme j'ai mis dans mon code que je viens de commenter pour mon dernier commit 
![image](https://user-images.githubusercontent.com/43904633/116761512-8c08e280-aa20-11eb-9e47-618287b3cc2c.png)

Le nombre de PC 130 prend tous la place pour le /24 ce qui ne permet pas de continuer le découpage, puisque comme préciser dans le README, Je ne prend en compte que les reseaux de classe C. 

Du coup, les données suivantes ne sont pas prises en charge,

Cependant, avec le commit **### e81a8fa57af3c99fe985c63c124d471343cb532b** que je viens de réaliser,

Cela permet de gérer la continuité, 

Vous pouvez maintenant mettre à jour le code et réessayer.

` Note: Ceci n'est pas donc un bug, mais une demande de fonctionnalité `

**Comment by gaetan1903** [comment]
Résultat après commit e81a8fa

![image](https://user-images.githubusercontent.com/43904633/116762064-fc643380-aa21-11eb-9472-be65d753a4ec.png)
